### ISSUE TITLE
Playback fails randomly

### ISSUE THREAD

**Issue by uloco** [dbrgn/orochi#54] opened 2015-03-25 11:54 UTC
When I try to play some mixes, there is a 'do you experience network problems' error, but my Internet works just fine. It's just that some playlists (and there are a lot) won't be played and others will. How can I help you find this bug?? Are there any reports or logs I can find and file?

**Comment by dbrgn** [comment] 2015-03-25 13:12
I did't use Orochi in a while, but I'll try to use it more over the next few days, maybe I'll experience the same issues :)

The error message actually occurs when mplayer doesn't start playback inside 15 seconds. Maybe some of the songs that 8tracks loads are simply served from a very busy server?

**Comment by dbrgn** [comment] 2015-03-25 13:34
Just experienced this after the first 3 songs :) And I found the problem:

Some songs are hosted on Soundcloud. These URLs return a HTTP 302 status code, which is not supported by mplayer.

**Comment by dbrgn** [comment] 2015-03-25 13:34
Therefore this is a duplicate of #52.

**Closed by dbrgn** 2015-03-25 13:34 UTC
Labels: bug

**Comment by dbrgn** [comment] 2015-03-25 14:49
Version 0.1.2 is on PyPI! Hope that resolves the playback issues.
